"""Tests for estimating a risk elasticity from delivery history.

The tests that matter most here are not the ones checking the arithmetic — they are
the ones checking the refusals. An estimator that returns a confident number from
five noisy periods is worse than no estimator, because it launders an assumption
into a measurement.
"""

from __future__ import annotations

import math
import random

import pytest

from scrcae.calibration import (
    CALIBRATION_VERSION,
    CONFIDENCE_LEVEL,
    MIN_OBSERVATIONS,
    MIN_PERIODS_ABOVE_ANCHOR,
    DeliveryObservation,
    FitQuality,
    calibrate_elasticity,
)

ANCHOR = 80.0


def observation(price: float, rate: float, period: str = "2025-Q1") -> DeliveryObservation:
    return DeliveryObservation(period=period, market_price=price, disruption_rate=rate)


def exact_series(
    elasticity: float,
    baseline: float,
    prices: list[float],
    *,
    anchor: float = ANCHOR,
) -> list[DeliveryObservation]:
    """History generated by the model with no noise, so the answer is known."""
    rows = []
    for index, price in enumerate(prices):
        deviation = max((price - anchor) / anchor, 0.0)
        rows.append(
            observation(price, baseline * (1.0 + elasticity * deviation), f"P{index:02d}")
        )
    return rows


PRICES_WITH_SPREAD = [72.0, 80.0, 84.0, 88.0, 96.0, 104.0, 78.0, 92.0, 100.0, 86.0, 76.0, 108.0]


class TestTheEstimatorRecoversAnElasticityItCanSee:
    def test_a_noiseless_series_returns_the_elasticity_that_generated_it(self) -> None:
        fit = calibrate_elasticity(
            exact_series(0.40, 0.05, PRICES_WITH_SPREAD), anchor=ANCHOR
        )

        assert fit.quality is FitQuality.USABLE
        assert fit.elasticity == pytest.approx(0.40, abs=1e-9)
        assert fit.baseline_disruption_rate == pytest.approx(0.05, abs=1e-9)
        assert fit.r_squared == pytest.approx(1.0, abs=1e-9)

    def test_the_elasticity_is_scale_free_in_the_disruption_measure(self) -> None:
        """Percent or fraction must give the same answer.

        A user who keeps disruption as 5.0 rather than 0.05 should not get an
        elasticity a hundred times different. This holds because the estimate is a
        ratio of slope to intercept, and it is worth pinning because a future change
        that subtracts a mean or clips to [0, 1] would break it.
        """
        as_fraction = calibrate_elasticity(
            exact_series(0.35, 0.04, PRICES_WITH_SPREAD), anchor=ANCHOR
        )
        as_percent = calibrate_elasticity(
            exact_series(0.35, 4.0, PRICES_WITH_SPREAD), anchor=ANCHOR
        )

        assert as_fraction.elasticity == pytest.approx(as_percent.elasticity, abs=1e-9)

    def test_periods_below_anchor_inform_the_baseline_and_not_the_slope(self) -> None:
        """The one-sided policy, stated as a test rather than a comment.

        Two histories share every above-anchor period; one adds cheap-market periods
        at the same baseline disruption. The elasticity must not move.
        """
        above_only = exact_series(0.30, 0.06, [80.0, 84.0, 90.0, 96.0, 102.0, 108.0, 88.0, 94.0])
        with_cheap = above_only + [
            observation(price, 0.06, f"cheap{index}")
            for index, price in enumerate([60.0, 64.0, 70.0, 74.0])
        ]

        assert calibrate_elasticity(above_only, anchor=ANCHOR).elasticity == pytest.approx(
            calibrate_elasticity(with_cheap, anchor=ANCHOR).elasticity, abs=1e-9
        )

    def test_two_sided_mode_lets_cheap_periods_pull_the_slope(self) -> None:
        """The asymmetry is an assumption, so the switch has to be real.

        With ``one_sided=False`` the same cheap-market periods now carry negative
        deviations, and a flat disruption rate across them therefore drags the fitted
        elasticity down. If this test ever passes with an unchanged estimate, the
        switch has stopped being wired through.
        """
        rows = exact_series(0.30, 0.06, [80.0, 90.0, 100.0, 110.0, 86.0, 96.0, 106.0, 92.0])
        rows += [observation(price, 0.06, f"cheap{i}") for i, price in enumerate([56.0, 64.0, 72.0])]

        one_sided = calibrate_elasticity(rows, anchor=ANCHOR, one_sided=True)
        two_sided = calibrate_elasticity(rows, anchor=ANCHOR, one_sided=False)

        assert one_sided.elasticity == pytest.approx(0.30, abs=1e-9)
        assert two_sided.elasticity is not None
        assert two_sided.elasticity < one_sided.elasticity
        assert two_sided.one_sided is False


class TestTheEstimatorRefusesRatherThanGuesses:
    def test_thin_history_is_refused_by_name(self) -> None:
        fit = calibrate_elasticity(
            exact_series(0.4, 0.05, [80.0, 88.0, 96.0, 104.0]), anchor=ANCHOR
        )

        assert fit.quality is FitQuality.TOO_FEW_OBSERVATIONS
        assert fit.elasticity is None
        assert str(MIN_OBSERVATIONS) in fit.summary()

    def test_a_market_that_never_ran_hot_cannot_identify_an_elasticity(self) -> None:
        """Ten years of cheap crude tell you nothing about expensive crude."""
        rows = [
            observation(price, 0.05, f"P{index}")
            for index, price in enumerate([60.0, 64.0, 68.0, 70.0, 72.0, 74.0, 76.0, 78.0, 79.0, 80.0])
        ]

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.quality is FitQuality.TOO_FEW_PERIODS_ABOVE_ANCHOR
        assert fit.elasticity is None
        assert fit.periods_above_anchor == 0
        assert str(MIN_PERIODS_ABOVE_ANCHOR) in fit.summary()

    def test_one_repeated_price_level_is_not_variation(self) -> None:
        """Twelve readings of the same two prices is one comparison, not twelve."""
        rows = [observation(80.0, 0.05, f"low{i}") for i in range(6)]
        rows += [observation(96.0, 0.08, f"high{i}") for i in range(6)]

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.quality is FitQuality.NO_DEVIATION_VARIATION
        assert fit.elasticity is None

    def test_prices_differing_in_the_twelfth_decimal_do_not_count_as_variation(self) -> None:
        rows = [observation(80.0, 0.05, f"low{i}") for i in range(6)]
        rows += [
            observation(96.0 + i * 1e-11, 0.08, f"high{i}") for i in range(6)
        ]

        assert calibrate_elasticity(rows, anchor=ANCHOR).quality is (
            FitQuality.NO_DEVIATION_VARIATION
        )

    def test_a_flat_disruption_column_is_named_as_such(self) -> None:
        """A node that never failed has no baseline to be elastic about."""
        rows = [
            observation(price, 0.0, f"P{index}")
            for index, price in enumerate(PRICES_WITH_SPREAD)
        ]

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.quality is FitQuality.NON_POSITIVE_BASELINE
        assert fit.elasticity is None
        assert "disruption column" in fit.summary()

    def test_a_negative_estimate_is_surfaced_as_a_hedge_claim_not_hidden(self) -> None:
        """Reporting the number and refusing to bless it are different acts.

        Clamping at zero would erase a finding the user needs to see: their records
        say this market moves the wrong way, which means either the anchor is wrong,
        the node is mismapped, or the market genuinely hedges them.
        """
        rows = exact_series(-0.30, 0.08, PRICES_WITH_SPREAD)

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.quality is FitQuality.WRONG_SIGN
        assert fit.elasticity is not None and fit.elasticity < 0.0
        assert fit.is_usable is False
        assert "hedge claim" in fit.summary()

    def test_pure_noise_is_usually_refused_and_at_close_to_the_nominal_rate(self) -> None:
        """The estimator's false-positive rate, measured rather than asserted.

        This test began life asserting that one particular noise history was refused,
        and it failed: at seed 11, forty independent draws happen to show a
        relationship significant at 5%. That was the test being wrong, not the
        estimator — but it is exactly the failure mode that matters, so it is now
        checked properly. Across many independent noise histories the share promoted
        to USABLE must sit near the nominal level implied by the interval.

        Two-sided: too high means the estimator launders coincidences, and too low
        means the interval is so conservative that nothing will ever calibrate and
        users will go back to typing elasticities by hand.
        """
        histories = 200
        promoted = 0
        for seed in range(histories):
            rng = random.Random(seed)
            rows = [
                observation(
                    80.0 + 30.0 * rng.random(), 0.05 + 0.02 * rng.random(), f"P{index}"
                )
                for index in range(40)
            ]
            if calibrate_elasticity(rows, anchor=ANCHOR, draws=400).is_usable:
                promoted += 1

        nominal = 1.0 - CONFIDENCE_LEVEL
        assert promoted / histories <= nominal * 2.0, (
            f"{promoted}/{histories} pure-noise histories were promoted to calibrated, "
            f"against a nominal {nominal:.0%}"
        )
        assert promoted >= 1, (
            "not one noise history in 200 was promoted, which means the interval is "
            "far wider than it claims and nothing real will ever calibrate either"
        )

    def test_a_history_with_no_relationship_says_so_in_words(self) -> None:
        """The wording of the refusal, on a history known to contain nothing.

        Seed chosen because it lands in the majority case above; the rate itself is
        covered by the preceding test.
        """
        rng = random.Random(0)
        rows = [
            observation(
                80.0 + 30.0 * rng.random(), 0.05 + 0.02 * rng.random(), f"P{index}"
            )
            for index in range(40)
        ]

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.is_usable is False
        if fit.quality is FitQuality.NOT_DISTINGUISHABLE_FROM_ZERO:
            assert fit.interval_spans_zero
            assert "do not establish" in fit.summary()

    def test_a_real_signal_under_noise_survives_and_is_marked_usable(self) -> None:
        """The counterpart to the test above: refusal must not be the only outcome."""
        rng = random.Random(7)
        rows = []
        for index in range(60):
            price = 70.0 + 45.0 * rng.random()
            deviation = max((price - ANCHOR) / ANCHOR, 0.0)
            clean = 0.05 * (1.0 + 0.9 * deviation)
            rows.append(observation(price, max(0.0, clean + rng.gauss(0.0, 0.002)), f"P{index}"))

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.quality is FitQuality.USABLE
        assert fit.is_usable
        assert fit.elasticity == pytest.approx(0.9, abs=0.25)
        assert fit.interval_low is not None and fit.interval_low > 0.0

    def test_an_impossible_anchor_raises_rather_than_returning_a_fit(self) -> None:
        """Bad *configuration* is a programming error; thin *data* is a finding.

        The distinction is deliberate: a zero anchor means the caller built the
        request wrong, and dividing by it would produce infinities that flow into a
        currency figure.
        """
        rows = exact_series(0.3, 0.05, PRICES_WITH_SPREAD)

        for bad in (0.0, -80.0, float("nan"), float("inf")):
            with pytest.raises(ValueError, match="anchor"):
                calibrate_elasticity(rows, anchor=bad)


class TestObservationsValidateThemselves:
    @pytest.mark.parametrize("price", [0.0, -1.0, float("nan"), float("inf")])
    def test_a_non_positive_or_non_finite_price_is_rejected_at_construction(self, price) -> None:
        with pytest.raises(ValueError, match="market_price"):
            observation(price, 0.05)

    def test_a_negative_disruption_rate_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="disruption_rate"):
            observation(80.0, -0.01)

    def test_a_non_finite_disruption_rate_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="disruption_rate"):
            observation(80.0, float("nan"))


class TestTheIntervalIsReproducibleAndSelfContained:
    def test_the_same_records_give_the_same_interval(self) -> None:
        """The audit ledger promises a run can be reproduced from its inputs.

        A bootstrap seeded from the clock would break that promise quietly: the plan
        would be identical and the confidence interval beside it would not.
        """
        rows = exact_series(0.4, 0.05, PRICES_WITH_SPREAD)
        rows = [
            observation(o.market_price, o.disruption_rate * (1.0 + 0.01 * i), o.period)
            for i, o in enumerate(rows)
        ]

        first = calibrate_elasticity(rows, anchor=ANCHOR)
        second = calibrate_elasticity(rows, anchor=ANCHOR)

        assert first.interval_low == second.interval_low
        assert first.interval_high == second.interval_high

    def test_a_different_seed_moves_the_interval_but_not_the_estimate(self) -> None:
        rows = exact_series(0.4, 0.05, PRICES_WITH_SPREAD)
        rows = [
            observation(o.market_price, o.disruption_rate * (1.0 + 0.02 * (i % 5)), o.period)
            for i, o in enumerate(rows)
        ]

        first = calibrate_elasticity(rows, anchor=ANCHOR, seed=1, draws=400)
        second = calibrate_elasticity(rows, anchor=ANCHOR, seed=2, draws=400)

        assert first.elasticity == pytest.approx(second.elasticity, abs=1e-12)
        assert (first.interval_low, first.interval_high) != (
            second.interval_low,
            second.interval_high,
        )

    def test_calibrating_does_not_disturb_the_global_random_stream(self) -> None:
        """F10, pinned for the calibrator.

        The acquired system seeded the global RNG inside a simulation, so running one
        changed every other draw in the process. Any new estimator that resamples has
        to be held to the same standard.
        """
        random.seed(4242)
        expected = [random.random() for _ in range(5)]

        random.seed(4242)
        calibrate_elasticity(exact_series(0.4, 0.05, PRICES_WITH_SPREAD), anchor=ANCHOR)
        after = [random.random() for _ in range(5)]

        assert after == expected


class TestTheFitExplainsItselfToItsReaders:
    def test_every_fit_carries_the_standing_caveats_including_refusals(self) -> None:
        """The causal and effectiveness caveats are not conditional on a good fit.

        They are properties of the method, so a refused fit must carry them too — the
        user reading "collect more history" needs to know what the number would and
        would not mean once they have it.
        """
        for rows in (
            exact_series(0.4, 0.05, PRICES_WITH_SPREAD),
            exact_series(0.4, 0.05, [80.0, 88.0, 96.0]),
        ):
            fit = calibrate_elasticity(rows, anchor=ANCHOR)
            joined = " ".join(fit.notes)
            assert "not the causal effect" in joined
            assert "constant fraction of node risk" in joined

    def test_a_weak_relationship_is_called_out_in_the_notes(self) -> None:
        rng = random.Random(3)
        rows = []
        for index in range(50):
            price = 70.0 + 40.0 * rng.random()
            deviation = max((price - ANCHOR) / ANCHOR, 0.0)
            rows.append(
                observation(
                    price, max(0.0, 0.05 * (1.0 + 0.5 * deviation) + rng.gauss(0, 0.03)), f"P{index}"
                )
            )

        fit = calibrate_elasticity(rows, anchor=ANCHOR)

        assert fit.r_squared is not None and fit.r_squared < 0.2
        assert any("Most of what happens to this node is not this market" in n for n in fit.notes)

    def test_provenance_is_flat_json_safe_and_names_the_method(self) -> None:
        """It has to survive ``canonical_json`` on the way into the audit ledger."""
        fit = calibrate_elasticity(exact_series(0.4, 0.05, PRICES_WITH_SPREAD), anchor=ANCHOR)

        provenance = fit.provenance()

        assert provenance["method"] == CALIBRATION_VERSION
        assert provenance["quality"] == "usable"
        assert provenance["anchor"] == ANCHOR
        for value in provenance.values():
            assert value is None or isinstance(value, (str, int, float, bool))
            if isinstance(value, float):
                assert math.isfinite(value)

    def test_the_summary_of_a_refusal_never_contains_a_number_to_copy(self) -> None:
        """A user must not be able to lift a figure out of a refusal message.

        If the summary said "elasticity 0.31, but only 4 periods", 0.31 would end up
        typed into the exposure table by the end of the week.
        """
        fit = calibrate_elasticity(exact_series(0.4, 0.05, [80.0, 88.0, 96.0]), anchor=ANCHOR)

        assert fit.elasticity is None
        assert "lasticity" not in fit.summary() or "estimate an elasticity" in fit.summary()


class TestTheIntervalIsHeldToItsClaim:
    """Coverage, measured. The one property an interval either has or does not.

    Every other test here checks that the estimator says the right words. These check
    that the number beside the words means what it says — that a 95% interval contains
    the truth about 95% of the time. Without this, "95% interval" is decoration, and a
    future change to the resampling could quietly turn it into a 70% interval while
    every other test in the file kept passing.
    """

    TRUE_ELASTICITY = 0.9
    BASELINE = 5.5
    ANCHOR = 79.0

    def history(self, seed: int, *, periods: int = 60, price_persistence: float = 0.0) -> list:
        """Simulated delivery history with a known elasticity.

        ``price_persistence`` makes the market an AR(1) process rather than independent
        draws, which is what a commodity actually is. The disruption series carries its
        own persistence in every case: a bad month follows a bad month.
        """
        rng = random.Random(seed)
        rows: list[DeliveryObservation] = []
        price = self.ANCHOR
        error = 0.0
        for index in range(periods):
            if price_persistence:
                price = max(20.0, self.ANCHOR + price_persistence * (price - self.ANCHOR) + rng.gauss(0.0, 9.0))
            else:
                price = 58.0 + 68.0 * rng.random()
            deviation = max((price - self.ANCHOR) / self.ANCHOR, 0.0)
            error = 0.5 * error + rng.gauss(0.0, 0.55)
            rows.append(
                observation(
                    price,
                    max(0.0, self.BASELINE * (1.0 + self.TRUE_ELASTICITY * deviation) + error),
                    f"P{index:02d}",
                )
            )
        return rows

    def measure(self, *, price_persistence: float, replications: int = 120) -> tuple[float, float]:
        covered = 0
        usable = 0
        estimates: list[float] = []
        for seed in range(replications):
            fit = calibrate_elasticity(
                self.history(90_000 + seed, price_persistence=price_persistence),
                anchor=self.ANCHOR,
                seed=seed,
                draws=300,
            )
            if fit.elasticity is None or fit.interval_low is None or fit.interval_high is None:
                continue
            usable += 1
            estimates.append(fit.elasticity)
            if fit.interval_low <= self.TRUE_ELASTICITY <= fit.interval_high:
                covered += 1
        assert usable >= replications * 0.9, "too many replications produced no interval to judge"
        return covered / usable, sum(estimates) / len(estimates)

    def test_the_point_estimate_is_unbiased_even_when_the_interval_is_optimistic(self) -> None:
        """Which of the two is wrong matters.

        A biased estimator would mean every calibrated multiplier in the product is
        systematically off. An optimistic interval means the number is right on average
        and we are slightly too confident about it. The second is a caveat; the first
        would be a reason not to ship this at all.
        """
        for persistence in (0.0, 0.85):
            _, mean_estimate = self.measure(price_persistence=persistence)
            assert mean_estimate == pytest.approx(self.TRUE_ELASTICITY, abs=0.08), (
                f"mean estimate {mean_estimate:.3f} against a true {self.TRUE_ELASTICITY} "
                f"at price persistence {persistence}"
            )

    def test_coverage_is_near_nominal_with_independent_prices(self) -> None:
        """Measured at about 91% against a nominal 95% over four hundred replications.

        The floor sits below the measured value because this is a stochastic
        measurement and a test that fails on a fair coin is worse than no test. It is
        high enough to catch the failures that matter: resampling residuals
        independently instead of in blocks, or dropping the bootstrap for textbook
        standard errors, both land far below it.
        """
        coverage, _ = self.measure(price_persistence=0.0)

        assert coverage >= 0.85, (
            f"coverage {coverage:.3f} against a nominal {CONFIDENCE_LEVEL}: the interval "
            f"is claiming materially more than it delivers"
        )
        assert coverage <= CONFIDENCE_LEVEL + 0.05, (
            f"coverage {coverage:.3f} exceeds the nominal {CONFIDENCE_LEVEL}: an interval "
            f"wider than it claims is also mis-labelled, and it costs usable fits"
        )

    def test_coverage_degrades_only_mildly_when_the_market_is_persistent(self) -> None:
        """The documented shortfall, pinned so it cannot quietly get worse.

        Measured at about 88% against a nominal 95% for an AR(1) market with
        persistence 0.85 — a real shortfall, documented in the module and not papered
        over. The floor is set below the measurement for the same reason as above.
        """
        coverage, _ = self.measure(price_persistence=0.85)

        assert coverage >= 0.80, (
            f"coverage collapsed to {coverage:.3f} for a persistent market; the "
            f"moving-block resampling is no longer doing its job"
        )
