"""Delivery history in, calibrated elasticity out — and the joins that go wrong.

The engine's tests cover the estimator. These cover the two things around it that
would break a correct estimator: parsing what a person pasted into a spreadsheet, and
joining their delivery months to a market's price months.
"""

from __future__ import annotations

import pandas as pd
import pytest

from scrcae.calibration import CALIBRATION_VERSION, FitQuality

from app import adapters
from app.services.calibration import calibrate_exposures, records_from_run
from app.services.feeds import PriceHistory, PricePoint, StaticProvider

NODE_IDS = ["N1", "N2"]
ANCHOR = 80.0

# A market that spends part of its life above the anchor of 80, which is the only
# reason an elasticity is estimable at all.
PRICES = {
    "2025-01": 70.0,
    "2025-02": 76.0,
    "2025-03": 84.0,
    "2025-04": 88.0,
    "2025-05": 96.0,
    "2025-06": 104.0,
    "2025-07": 92.0,
    "2025-08": 78.0,
    "2025-09": 100.0,
    "2025-10": 86.0,
    "2025-11": 108.0,
    "2025-12": 82.0,
}

TRUE_ELASTICITY = 0.5
BASELINE_PCT = 4.0


def disruption_for(period: str) -> float:
    """Disruption generated by the model, so the recoverable answer is known."""
    deviation = max((PRICES[period] - ANCHOR) / ANCHOR, 0.0)
    return BASELINE_PCT * (1.0 + TRUE_ELASTICITY * deviation)


def history_frame(node_id: str = "N1", periods=None) -> pd.DataFrame:
    periods = list(periods or PRICES)
    return pd.DataFrame(
        [
            {
                adapters.COL_HIST_NODE_ID: node_id,
                adapters.COL_HIST_PERIOD: period,
                adapters.COL_HIST_DISRUPTION: disruption_for(period),
            }
            for period in periods
        ]
    )


def exposure(node_id: str = "N1", elasticity: float = 0.2, anchor: float = ANCHOR):
    return adapters.NodeExposure(
        node_id=node_id, symbol="BZ=F", anchor=anchor, elasticity=elasticity
    )


def provider_with_history(prices=None) -> StaticProvider:
    return StaticProvider(
        prices={"BZ=F": 92.0},
        histories={"BZ=F": tuple((p, v) for p, v in (prices or PRICES).items())},
    )


# --------------------------------------------------------------------------- #
# Reading the delivery sheet
# --------------------------------------------------------------------------- #


class TestParsingWhatSomebodyPasted:
    def test_a_clean_sheet_parses_every_row(self) -> None:
        records, rejections = adapters.build_delivery_records(history_frame(), NODE_IDS)

        assert len(records) == len(PRICES)
        assert not rejections.items
        assert records[0].node_id == "N1"

    @pytest.mark.parametrize(
        "written,expected",
        [
            ("2026-07", "2026-07"),
            ("2026-7", "2026-07"),
            ("2026/07", "2026-07"),
            ("2026-07-14", "2026-07"),
            ("07/2026", "2026-07"),
            ("Jul 2026", "2026-07"),
            ("2026-07-31", "2026-07"),
        ],
    )
    def test_the_period_formats_people_actually_type_all_reduce_to_a_month(
        self, written, expected
    ) -> None:
        """Rejecting a date because it has a day in it teaches users to fight the tool."""
        assert adapters.normalise_period(written) == expected

    @pytest.mark.parametrize("written", ["", "Q3", "last summer", "2026-13", "13/2026", "-"])
    def test_a_period_that_cannot_be_read_is_refused_rather_than_guessed(
        self, written
    ) -> None:
        """The join is by month, so a guessed month is a silently wrong pairing.

        This is the failure with no symptom: the estimator would run happily on
        delivery performance matched to the wrong month's price and return a confident
        number about a relationship that was never in the data.
        """
        assert adapters.normalise_period(written) == ""

    def test_an_unreadable_period_is_reported_with_the_row_number(self) -> None:
        frame = history_frame()
        frame.loc[3, adapters.COL_HIST_PERIOD] = "third quarter"

        records, rejections = adapters.build_delivery_records(frame, NODE_IDS)

        assert len(records) == len(PRICES) - 1
        assert any("History row 4" in item for item in rejections.items)

    def test_two_rows_for_the_same_node_and_month_are_refused_not_averaged(self) -> None:
        """Averaging would produce a figure belonging to neither definition.

        A duplicate month is either a double paste or two teams measuring disruption
        differently. Both need a human; neither needs a mean.
        """
        frame = pd.concat([history_frame(), history_frame(periods=["2025-03"])])

        records, rejections = adapters.build_delivery_records(frame, NODE_IDS)

        assert len(records) == len(PRICES)
        assert any("duplicate" in item for item in rejections.items)

    def test_a_rate_above_one_hundred_percent_is_caught_as_a_unit_error(self) -> None:
        """The commonest paste error in this column, and it inflates every figure.

        A raw incident count in a percentage column would raise the fitted baseline and
        leave the elasticity plausible, so nothing downstream would look wrong.
        """
        frame = history_frame()
        frame.loc[2, adapters.COL_HIST_DISRUPTION] = 340.0

        records, rejections = adapters.build_delivery_records(frame, NODE_IDS)

        assert len(records) == len(PRICES) - 1
        assert any("not a count" in item for item in rejections.items)

    def test_a_row_naming_an_unknown_node_is_reported_and_the_rest_survive(self) -> None:
        frame = pd.concat([history_frame(), history_frame(node_id="GHOST", periods=["2025-05"])])

        records, rejections = adapters.build_delivery_records(frame, NODE_IDS)

        assert {r.node_id for r in records} == {"N1"}
        assert any("GHOST" in item for item in rejections.items)

    def test_a_wholly_blank_row_is_not_an_error(self) -> None:
        """The data editor adds one, so treating it as an error would mean the table is
        never valid while a user is typing in it."""
        frame = pd.concat(
            [history_frame(), pd.DataFrame([{c: None for c in adapters.HISTORY_COLUMNS}])]
        )

        records, rejections = adapters.build_delivery_records(frame, NODE_IDS)

        assert len(records) == len(PRICES)
        assert not rejections.items

    def test_renaming_a_node_does_not_delete_its_delivery_history(self) -> None:
        """Alignment keeps rows, unlike the exposure sheet's alignment.

        Delivery history is evidence of what happened. An intervention rename is an
        edit to a plan, and it must not destroy records — a user who renames back would
        otherwise find months of history gone with no undo.
        """
        aligned = adapters.align_history_frame(history_frame(node_id="OLD"))

        assert len(aligned) == len(PRICES)
        assert set(aligned[adapters.COL_HIST_NODE_ID]) == {"OLD"}


# --------------------------------------------------------------------------- #
# Joining delivery months to market months
# --------------------------------------------------------------------------- #


class TestCalibratingAnExposure:
    def test_a_clean_history_recovers_the_elasticity_that_generated_it(self) -> None:
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures([exposure()], records, provider=provider_with_history())

        assert len(run.calibrations) == 1
        fit = run.calibrations[0].fit
        assert fit is not None
        assert fit.elasticity == pytest.approx(TRUE_ELASTICITY, abs=1e-6)
        assert fit.baseline_disruption_rate == pytest.approx(BASELINE_PCT, abs=1e-6)

    def test_percentages_and_fractions_give_the_same_elasticity(self) -> None:
        """So a user who keeps disruption as 0.04 rather than 4.0 is not punished."""
        frame = history_frame()
        as_fraction = frame.copy()
        as_fraction[adapters.COL_HIST_DISRUPTION] = (
            as_fraction[adapters.COL_HIST_DISRUPTION] / 100.0
        )

        records_pct, _ = adapters.build_delivery_records(frame, NODE_IDS)
        records_frac, _ = adapters.build_delivery_records(as_fraction, NODE_IDS)

        pct = calibrate_exposures([exposure()], records_pct, provider=provider_with_history())
        frac = calibrate_exposures([exposure()], records_frac, provider=provider_with_history())

        assert pct.calibrations[0].fit.elasticity == pytest.approx(
            frac.calibrations[0].fit.elasticity, abs=1e-9
        )

    def test_a_delivery_month_with_no_market_price_is_dropped_by_name(self) -> None:
        """Never matched to the nearest month. That is the silent off-by-one.

        The dropped periods are listed so the user can see the gap in their own terms
        rather than wondering why the period count is lower than their row count.
        """
        records, _ = adapters.build_delivery_records(
            pd.concat([history_frame(), history_frame(periods=["2025-01"]).assign(**{
                adapters.COL_HIST_PERIOD: "2019-05"
            })]),
            NODE_IDS,
        )

        run = calibrate_exposures([exposure()], records, provider=provider_with_history())
        calibration = run.calibrations[0]

        assert "2019-05" in calibration.unmatched_periods
        assert calibration.matched_periods == len(PRICES)
        assert "2019-05" in calibration.headline()

    def test_two_nodes_on_the_same_market_are_fitted_against_one_series(self) -> None:
        """Otherwise their elasticities are not comparable.

        Two nodes exposed to copper must be measured against the same definition of the
        price of copper, or the multiplier on one is not on the same footing as the
        other and adding them tells you nothing.
        """
        frame = pd.concat([history_frame("N1"), history_frame("N2")])
        records, _ = adapters.build_delivery_records(frame, NODE_IDS)

        run = calibrate_exposures(
            [exposure("N1"), exposure("N2")], records, provider=provider_with_history()
        )

        assert set(run.histories) == {"BZ=F"}
        assert len(run.calibrations) == 2
        assert run.calibrations[0].fit.elasticity == pytest.approx(
            run.calibrations[1].fit.elasticity, abs=1e-9
        )

    def test_a_node_with_no_history_is_blocked_with_a_reason_not_a_zero(self) -> None:
        run = calibrate_exposures([exposure("N2")], (), provider=provider_with_history())
        calibration = run.calibrations[0]

        assert calibration.fit is None
        assert calibration.can_adopt is False
        assert "No delivery history recorded for N2" in calibration.blocked

    def test_a_market_with_no_history_is_blocked_and_names_the_feed_reason(self) -> None:
        """A spot-only feed must read as "cannot calibrate", not as "no relationship"."""
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures(
            [exposure()], records, provider=StaticProvider(prices={"BZ=F": 92.0})
        )
        calibration = run.calibrations[0]

        assert calibration.fit is None
        assert calibration.can_adopt is False
        assert "No price history for BZ=F" in calibration.blocked
        assert "No history supplied" in calibration.history_status

    def test_calibrating_with_no_exposures_configured_says_so_plainly(self) -> None:
        run = calibrate_exposures([], (), provider=provider_with_history())

        assert run.calibrations == ()
        assert "no market exposure has been configured" in run.summary()

    def test_a_supplied_history_needs_no_network_at_all(self) -> None:
        """The seam that makes this testable, asserted rather than assumed.

        The provider raises if touched. If a future refactor reintroduces a fetch on
        this path, this test fails rather than the suite quietly acquiring a network
        dependency.
        """

        class Exploding:
            name = "exploding"
            symbol_help = ""

            def latest(self, symbols, *, timeout=4.0):
                raise AssertionError("the feed was contacted")

            def history(self, symbol, *, months=60, timeout=8.0):
                raise AssertionError("the feed was contacted")

        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures(
            [exposure()],
            records,
            provider=Exploding(),
            histories={
                "BZ=F": PriceHistory(
                    symbol="BZ=F",
                    points=tuple(PricePoint(p, v) for p, v in PRICES.items()),
                    status="Supplied",
                )
            },
        )

        assert run.calibrations[0].fit.elasticity == pytest.approx(TRUE_ELASTICITY, abs=1e-6)

    def test_the_delta_note_says_how_wrong_the_typed_number_was(self) -> None:
        """The usual point of a calibration is not the estimate, it is the gap."""
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures(
            [exposure(elasticity=0.1)], records, provider=provider_with_history()
        )

        note = run.calibrations[0].delta_note()
        assert "0.10" in note and "0.50" in note

    def test_an_entered_value_under_the_fit_is_called_below_it(self) -> None:
        """The direction word has to agree with the multiplier printed beside it.

        This test exists because the first version of the note printed entered/fitted
        (0.20) while labelling it with the direction of fitted/entered, so understating a
        risk elasticity was reported as being 'above the fit'. A wrong direction word here
        tells a reader their stale assumption is conservative when it is the opposite.
        """
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures(
            [exposure(elasticity=0.1)], records, provider=provider_with_history()
        )

        note = run.calibrations[0].delta_note()
        assert "0.20× the fit, below it" in note
        assert "above" not in note

    def test_an_entered_value_over_the_fit_is_called_above_it(self) -> None:
        """The other side of the same sentence."""
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)

        run = calibrate_exposures(
            [exposure(elasticity=1.0)], records, provider=provider_with_history()
        )

        note = run.calibrations[0].delta_note()
        assert "2.00× the fit, above it" in note
        assert "below" not in note


# --------------------------------------------------------------------------- #
# Storing a fit, and what makes a number calibrated
# --------------------------------------------------------------------------- #


class TestOnlyEvidenceMakesANumberCalibrated:
    def stored_run(self, elasticity: float = 0.2):
        records, _ = adapters.build_delivery_records(history_frame(), NODE_IDS)
        run = calibrate_exposures(
            [exposure(elasticity=elasticity)], records, provider=provider_with_history()
        )
        return run

    def test_only_adoptable_fits_are_stored_as_evidence(self) -> None:
        """A refused fit is not evidence, and a row in the saved file would look like it.

        Anyone opening a saved portfolio and seeing a calibration row would reasonably
        conclude the number beside it was measured.
        """
        run = self.stored_run()
        assert run.calibrations[0].can_adopt

        thin, _ = adapters.build_delivery_records(
            history_frame(periods=list(PRICES)[:4]), NODE_IDS
        )
        refused = calibrate_exposures([exposure()], thin, provider=provider_with_history())

        assert refused.calibrations[0].fit.quality is FitQuality.TOO_FEW_OBSERVATIONS
        assert records_from_run(refused) == ()
        assert len(records_from_run(run)) == 1

    def test_a_stored_fit_records_the_method_that_produced_it(self) -> None:
        stored = records_from_run(self.stored_run())[0]

        assert stored.method == CALIBRATION_VERSION
        assert stored.observations == len(PRICES)

    def test_an_exposure_matching_its_stored_fit_reads_as_calibrated(self) -> None:
        stored = records_from_run(self.stored_run())[0]
        adopted = exposure(elasticity=stored.elasticity)

        resolved = adapters.resolve_elasticity_sources([adopted], [stored])

        assert resolved[0].is_calibrated
        assert CALIBRATION_VERSION in resolved[0].elasticity_source

    def test_overtyping_a_calibrated_elasticity_silently_reverts_it_to_asserted(self) -> None:
        """The whole reason provenance is derived rather than stored beside the number.

        A "source" column would still say calibrated after the edit. Here the label is
        recomputed from evidence every run, so a number a person changed is a number a
        person is asserting — and it is labelled that way without anyone remembering to.
        """
        stored = records_from_run(self.stored_run())[0]
        edited = exposure(elasticity=stored.elasticity + 0.15)

        resolved = adapters.resolve_elasticity_sources([edited], [stored])

        assert resolved[0].is_calibrated is False
        assert resolved[0].elasticity_source == adapters.ASSERTED

    def test_moving_the_anchor_also_revokes_the_calibrated_label(self) -> None:
        """The elasticity is defined relative to the anchor it was fitted against.

        A fit against deviations from 80 says nothing about deviations from 95, and
        keeping the label would carry the authority of a measurement over to a quantity
        nobody measured.
        """
        stored = records_from_run(self.stored_run())[0]
        moved = exposure(elasticity=stored.elasticity, anchor=95.0)

        resolved = adapters.resolve_elasticity_sources([moved], [stored])

        assert resolved[0].is_calibrated is False

    def test_a_csv_round_trip_does_not_revoke_the_label(self) -> None:
        """The tolerance exists for this and only this.

        Saving and reloading a portfolio must not downgrade a calibrated elasticity,
        or the label would decay to "asserted" for everyone who closes the tab.
        """
        stored = records_from_run(self.stored_run())[0]
        frame = pd.DataFrame(
            [
                {
                    adapters.COL_CAL_NODE_ID: stored.node_id,
                    adapters.COL_CAL_SYMBOL: stored.symbol,
                    adapters.COL_CAL_ELASTICITY: stored.elasticity,
                    adapters.COL_CAL_ANCHOR: stored.anchor,
                    adapters.COL_CAL_METHOD: stored.method,
                    adapters.COL_CAL_OBS: stored.observations,
                }
            ]
        )
        reparsed, rejections = adapters.build_calibration_records(
            adapters.align_calibration_frame(pd.read_csv(pd.io.common.StringIO(frame.to_csv(index=False))))
        )

        assert not rejections.items
        resolved = adapters.resolve_elasticity_sources(
            [exposure(elasticity=stored.elasticity)], reparsed
        )
        assert resolved[0].is_calibrated

    def test_a_stored_row_with_no_method_cannot_vouch_for_anything(self) -> None:
        """It fails towards asserted, which is the safe direction."""
        frame = pd.DataFrame(
            [
                {
                    adapters.COL_CAL_NODE_ID: "N1",
                    adapters.COL_CAL_SYMBOL: "BZ=F",
                    adapters.COL_CAL_ELASTICITY: 0.5,
                    adapters.COL_CAL_ANCHOR: ANCHOR,
                    adapters.COL_CAL_METHOD: "",
                }
            ]
        )

        records, rejections = adapters.build_calibration_records(frame)

        assert records == ()
        assert any("method" in item for item in rejections.items)
        resolved = adapters.resolve_elasticity_sources([exposure(elasticity=0.5)], records)
        assert resolved[0].is_calibrated is False

    def test_a_forged_calibration_row_cannot_bless_an_arbitrary_number(self) -> None:
        """Hand-editing the evidence table is possible; making it agree is the barrier.

        This is not a security control — a determined user can edit both columns. It is
        a control against the accidental version, where a stale calibration row from a
        previous fit keeps vouching for a number that has since been changed.
        """
        forged = adapters.CalibrationRecord(
            node_id="N1",
            symbol="BZ=F",
            elasticity=0.5,
            anchor=ANCHOR,
            interval_low=0.4,
            interval_high=0.6,
            r_squared=0.9,
            observations=12,
            periods_above_anchor=8,
            method="hand-typed",
        )

        assert adapters.resolve_elasticity_sources([exposure(elasticity=2.0)], [forged])[
            0
        ].is_calibrated is False
        assert adapters.resolve_elasticity_sources([exposure(elasticity=0.5)], [forged])[
            0
        ].is_calibrated is True
